### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by kmazur99** [JasonWei512/code-radio-cli#16]
Add support for ARM architecture to make it compatible with Apple's M series processors.

**Comment by JasonWei512** [comment]
Currently ARM64 binary is not provided because I don't have ARM64 Mac, and [GitHub doesn't provide ARM64 CI runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). See https://github.com/JasonWei512/code-radio-cli/issues/5.

If you are using an ARM64 Mac, you can compile this program from source by [installing Rust toolchain](https://rustup.rs/) and running `cargo install code-radio-cli`.

**Comment by wangzhengbo** [comment]
> cargo install code-radio-cli

Compiling code-radio-cli v1.0.3
error[E0015]: cannot call non-const fn `std::sync::Mutex::<std::option::Option<Player>>::new` in statics
  --> /Users/wangzhengbo/.cargo/registry/src/github.com-1ecc6299db9ec823/code-radio-cli-1.0.3/src/main.rs:28:40
   |
28 | static PLAYER: Mutex<Option<Player>> = Mutex::new(None);
   |                                        ^^^^^^^^^^^^^^^^
   |
   = note: calls in statics are limited to constant functions, tuple structs and tuple variants

error[E0015]: cannot call non-const fn `std::sync::Mutex::<std::option::Option<ProgressBar>>::new` in statics
  --> /Users/wangzhengbo/.cargo/registry/src/github.com-1ecc6299db9ec823/code-radio-cli-1.0.3/src/main.rs:29:51
   |
29 | static PROGRESS_BAR: Mutex<Option<ProgressBar>> = Mutex::new(None);
   |                                                   ^^^^^^^^^^^^^^^^
   |
   = note: calls in statics are limited to constant functions, tuple structs and tuple variants

For more information about this error, try `rustc --explain E0015`.
error: could not compile `code-radio-cli` due to 2 previous errors
error: failed to compile `code-radio-cli v1.0.3`, intermediate artifacts can be found at `/var/folders/yj/lt1g82ks79d86d00l65pbzs00000gn/T/cargo-install8uBNFi`

mac arm安装报错: rustc版本是1.61.0

**Comment by JasonWei512** [comment]
@wangzhengbo
Upgrade Rust to latest version.

**Comment by esaaprillia** [comment]
i have tried building this in openwrt

**Comment by FLimburg** [comment]
On my M2:
Installing from cargo works fine.
Building release works fine.
Building debug has issues:

```
thread '<unnamed>' panicked at library/core/src/panicking.rs:218:5:
unsafe precondition(s) violated: slice::get_unchecked_mut requires that the index is within the slice
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
Abort trap: 6
```

**Comment by esaaprillia** [comment]
> On my M2: Installing from cargo works fine. Building release works fine. Building debug has issues:
> 
> ```
> thread '<unnamed>' panicked at library/core/src/panicking.rs:218:5:
> unsafe precondition(s) violated: slice::get_unchecked_mut requires that the index is within the slice
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread caused non-unwinding panic. aborting.
> Abort trap: 6
> ```

I haven't used this in a while. are you running radio-cli?

**Comment by FLimburg** [comment]
Just shamelessly stealing your code.
Was the best I could find for playing internet radio stations in rust.
I'm trying to implement a cli for https://radio.garden
The cli and the radio station itself is pretty smooth, I'll probably be using it every now and then. (<- referring to code radio there)

**Comment by FLimburg** [comment]
Just for completeness here the stack trace from your code. 
Mine changed already to not stumble over this. Not sure yet why.
Should I figure, I'll let you know.

```thread '<unnamed>' panicked at library/core/src/panicking.rs:218:5:
unsafe precondition(s) violated: slice::get_unchecked_mut requires that the index is within the slice
stack backtrace:
   0:        0x101128dc4 - std::backtrace_rs::backtrace::libunwind::trace::h6956fa18d4ab00eb
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:        0x101128dc4 - std::backtrace_rs::backtrace::trace_unsynchronized::h502bc8e06091c867
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:        0x101128dc4 - std::sys::backtrace::_print_fmt::hdbae9cccec38fd54
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/sys/backtrace.rs:66:9
   3:        0x101128dc4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h217270392019d164
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/sys/backtrace.rs:39:26
   4:        0x101145ee4 - core::fmt::rt::Argument::fmt::h03521b57b993b5fd
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/fmt/rt.rs:177:76
   5:        0x101145ee4 - core::fmt::write::he22fcab56bd3ec61
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/fmt/mod.rs:1449:21
   6:        0x101125c54 - std::io::Write::write_fmt::hb32eaafcfd249a19
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/io/mod.rs:1890:15
   7:        0x101128c78 - std::sys::backtrace::BacktraceLock::print::h115149c0b879e5c3
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/sys/backtrace.rs:42:9
   8:        0x101129b5c - std::panicking::default_hook::{{closure}}::h5c3a234feebd11a5
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:298:22
   9:        0x101129998 - std::panicking::default_hook::ha0b223ccc4379930
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:325:9
  10:        0x10112a68c - std::panicking::rust_panic_with_hook::h203f96c93e7ac62d
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:831:13
  11:        0x10112a230 - std::panicking::begin_panic_handler::{{closure}}::hcc8f653f753c0254
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:697:13
  12:        0x101129278 - std::sys::backtrace::__rust_end_short_backtrace::h911de07218b69a6c
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/sys/backtrace.rs:168:18
  13:        0x101129f10 - rust_begin_unwind
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:695:5
  14:        0x10116580c - core::panicking::panic_nounwind_fmt::runtime::h64a1ceac3685f305
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:117:22
  15:        0x10116580c - core::panicking::panic_nounwind_fmt::hc1d4bd06ab2bbbab
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/intrinsics/mod.rs:3886:9
  16:        0x101165884 - core::panicking::panic_nounwind::h96b8083b1a8e2dbd
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:218:5
  17:        0x100bd3b44 - <usize as core::slice::index::SliceIndex<[T]>>::get_unchecked_mut::precondition_check::h36186445ca9b8b60
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ub_checks.rs:68:21
  18:        0x100bd3af4 - <usize as core::slice::index::SliceIndex<[T]>>::get_unchecked_mut::h3477b03f6115d4ce
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ub_checks.rs:75:17
  19:        0x100bd3ab4 - core::slice::<impl [T]>::get_unchecked_mut::h9c69acc391c49d1a
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:705:24
  20:        0x1009cf26c - slice_deque::SliceDeque<T>::extend_desugared::he606792c11a24797
                               at /Users/flimburg/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slice-deque-0.3.0/src/lib.rs:1720:28
  21:        0x1009cff28 - <slice_deque::SliceDeque<T> as slice_deque::SpecExtend<T,I>>::spec_extend::h31738695b1c5802c
                               at /Users/flimburg/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slice-deque-0.3.0/src/lib.rs:2614:9
  22:        0x1009cff80 - <slice_deque::SliceDeque<T> as slice_deque::SpecExtend<&T,I>>::spec_extend::h7fddad655bc5b812
                               at /Users/flimburg/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slice-deque-0.3.0/src/lib.rs:2702:9
  23:        0x1009cead8 - <slice_deque::SliceDeque<T> as core::iter::traits::collect::Extend<&T>>::extend::h89c1b55056865c75
                               at /Users/flimburg/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slice-deque-0.3.0/src/lib.rs:2856:9
  24:        0x100908af4 - minimp3::Decoder<R>::refill::hec8ec173af9f7407
                               at /Users/flimburg/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/minimp3-0.5.1/src/lib.rs:199:9
  25:        0x10090818c - minimp3::Decoder<R>::next_frame::h00ee4ac807e12517
                               at /Users/flimburg/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/minimp3-0.5.1/src/lib.rs:177:22
  26:        0x10092fe50 - code_radio::mp3_stream_decoder::Mp3StreamDecoder<R>::new::h84b5ab2f36dfef15
                               at /Users/flimburg/priv/code-radio-cli/src/mp3_stream_decoder.rs:32:29
  27:        0x1008e87b4 - code_radio::player::Player::try_new::{{closure}}::hf1843479f9b728cf
                               at /Users/flimburg/priv/code-radio-cli/src/player.rs:38:30
  28:        0x1008f38a4 - std::sys::backtrace::__rust_begin_short_backtrace::h186a571ed1643747
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  29:        0x100928898 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h37b8966771ff89ba
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:559:17
  30:        0x1009233a8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha44a95b1c462580e
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  31:        0x1008f8c10 - std::panicking::try::do_call::h94ef678f88fe530e
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:587:40
  32:        0x100928cec - ___rust_try
  33:        0x100928678 - std::panicking::try::hd2abccb4c7a16cc3
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:550:19
  34:        0x100928678 - std::panic::catch_unwind::h6bcfc0c6e8155431
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:358:14
  35:        0x100928678 - std::thread::Builder::spawn_unchecked_::{{closure}}::hb85dcf9d50264532
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:557:30
  36:        0x1009322bc - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1b0480b18a7ac00b
                               at /Users/flimburg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  37:        0x10112c468 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h79019d5e89074f15
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/alloc/src/boxed.rs:1976:9
  38:        0x10112c468 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d739a27f97a48eb
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/alloc/src/boxed.rs:1976:9
  39:        0x10112c468 - std::sys::pal::unix::thread::Thread::new::thread_start::h6d53b1b0c047a3b9
                               at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/sys/pal/unix/thread.rs:106:17
  40:        0x18efa1c0c - __pthread_cond_wait
thread caused non-unwinding panic. aborting.
Abort trap: 6
```

**Comment by FLimburg** [comment]
Check out https://github.com/JasonWei512/code-radio-cli/pull/26

**Comment by JasonWei512** [comment]
Done in [v1.0.6](https://github.com/JasonWei512/code-radio-cli/releases/tag/v1.0.6)
